
name: "DockerPush"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: DockerPush
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: shuye72/jd-basetest
          dockerFile: docker/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          tag: test
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
